# Source: jxboot-helmfile-resources/templates/jenkins-x-docker-registry.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-x-docker-registry
  annotations:
    expose.config.fabric8.io/clusterip-port-if-empty-key: docker.registry
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
data:
  kaniko.flags: ""
  docker.registry: 328738327430.dkr.ecr.us-east-1.amazonaws.com
