jxRequirements:
  autoUpdate:
    enabled: false
    schedule: ""
  bootConfigURL: https://github.com/jenkins-x/jx3-boot-config
  buildPacks:
    buildPackLibrary:
      gitRef: master
      gitURL: https://github.com/jenkins-x/jxr-packs-kubernetes.git
  cluster:
    clusterName: jx-eks
    environmentGitOwner: makmk
    gitKind: github
    gitName: github
    gitServer: https://github.com
    namespace: jx
    provider: eks
    region: us-east-1
    registry: 233487312884.dkr.ecr.us-east-1.amazonaws.com
  environments:
  - ingress:
      domain: ""
      externalDNS: true
      namespaceSubDomain: -dev.
      tls:
        email: ""
        enabled: false
        production: false
    key: dev
    owner: makmk
    repository: jenkins-x-config
  - ingress:
      domain: ""
      externalDNS: true
      namespaceSubDomain: -stage.
      tls:
        email: ""
        enabled: false
        production: false
    key: staging
  - ingress:
      domain: ""
      externalDNS: true
      namespaceSubDomain: -prod.
      tls:
        email: ""
        enabled: false
        production: false
    key: production
  gitops: true
  ingress:
    domain: ""
    externalDNS: true
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kaniko: true
  pipelineUser:
    username: makmk
  repository: nexus
  secretStorage: vault
  storage:
    backup:
      enabled: false
      url: ""
    logs:
      enabled: true
      url: s3://logs-jx-eks-20200922182948233900000007
    reports:
      enabled: true
      url: s3://reports-jx-eks-20200922182948233400000004
    repository:
      enabled: true
      url: s3://repository-jx-eks-20200922182948233400000005
  vault:
    aws:
      dynamoDBRegion: us-east-1
      dynamoDBTable: vault-unseal-jx-eks-IJEonIeb
      kmsKeyId: c6780160-951d-4077-848a-52fde2e37949
      kmsRegion: us-east-1
      s3Bucket: vault-unseal-jx-eks-20200922182948233800000006
      s3Region: us-east-1
  velero:
    schedule: ""
    ttl: ""
  versionStream:
    ref: master
    url: https://github.com/jenkins-x/jxr-versions.git
  webhook: lighthouse
